export const GET_REVIEWS = 'GET_REVIEWS';
export const GET_COUNT_REVIEWS = 'GET_COUNT_REVIEWS';
export const CHANGE_CURRENT_PAGE = 'CHANGE_CURRENT_PAGE';
export const TOGGLE_DIALOG = 'TOGGLE_DIALOG';
export const TOGGLE_DIALOG_WINDOWPAY = 'TOGGLE_DIALOG_WINDOWPAY';
export const TOGGLE_DIALOG_DELETE = 'TOGGLE_DIALOG_DELETE';
export const SET_ALERT = 'SET_ALERT';
